#extra packages required but recognised by renv (probably suggests rather than imports field of package description file)
requireNamespace("visNetwork")
requireNamespace("rticles")
requireNamespace("curl")
requireNamespace("RSQLite")